---

- name: Show version
  hosts: lsw3
  gather_facts: false

  tasks:
    - name: running **show version**
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
