---

- name: Show ip int brief
  hosts: lsw3
  gather_facts: false

  tasks:
    - name: running **show ip int br**
      ios_command:
        commands: show ip int br
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
